# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Test, and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./NMDB/NMDB.sln

      # Build project
      - name: Build
        run: dotnet build --no-restore ./NMDB/NMDB.sln

      # Run tests
      - name: Test
        run: dotnet test --no-build --verbosity normal ./NMDB/NMDB.sln

  build_and_push_container:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://reeliocr.azurecr.io/
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      # Build and push container image
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./NMDB
          push: true
          tags:   reeliocr.azurecr.io/nmdb-api:${{ github.sha }}
          file: ./NMDB/Dockerfile

  deploy_to_azure:
    runs-on: ubuntu-latest
    needs: build_and_push_container
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NMDB-API'
          slot-name: 'Production' 
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_2ea17b288cb24da989d0fd87b8866f59 }}
          images: 'reeliocr.azurecr.io/${{ secrets.CONTAINER_USERNAME }}/r:${{ github.sha }}'
